name: bruce_omukoko_portfolio
description: "Bruce Omukoko's portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  #webview_flutter_platform_interface: ^2.10.0
  url_launcher: ^6.2.5
  share_plus: ^7.1.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.7
  webview_flutter_web: 
  phone_form_field: 
  rive: ^0.13.1
  cloud_firestore: ^4.16.0
  firebase_core: ^2.28.0
  animations: ^2.0.7
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
