name: bruce_omukoko_portfolio
description: "Bruce Omukoko's portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter:
  intl: ^0.18.0
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.2.5
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.7
  rive: ^0.13.1
  animations: ^2.0.7
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  spinner_date_picker:
  lru_memory_cache:
#  duration_picker:
  visibility_detector: ^0.4.0+2
  scrollable_positioned_list: ^0.3.8
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - bruc3balo/assets/
