name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Copy assets
        run: |
          mkdir -p build/web/assets
          cp -r bruc3balo/assets/* build/web/assets/

      - name: Build
        run: flutter build web --wasm --base-href "/bruc3balo.github.io/" --release

      - name: Configure 404
        run: |
          cp build/web/index.html build/web/404.html

      - name: Add CNAME
        run: echo "bruc3balo.github.io" > build/web/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true